Updating link in README to noetic in order to compile
wsnewman/learning_ros pull request #25
Opened 2022-03-08 04:57 UTC by mfkenson

fixing file paths in launch files

2022-03-14 14:15 UTC, leegs approved these changes
Thank you for these edits.

2022-03-14 14:16 UTC, leegs commented on README.md
> +`git clone --recursive https://github.com/wsnewman/learning_ros.git`
This edit will be accepted.

2022-03-14 14:18 UTC, leegs commented on README.md
> +`git clone --recursive https://github.com/wsnewman/learning_ros_external_pkgs_noetic`
This repository will not exist.  The learning_ros_external_pkgs repository is working with both Melodic and Noetic at this time.  (At least is should be.)  If the updated version does not work for Noetic, please submit an issue on that repository. 

This edit will not be accepted as it will not be necessary.

2022-03-14 14:19 UTC, leegs requested changes
Please remove the change for the "learning_ros_external_pkgs" line as it is being address separately.

2022-03-14 14:36 UTC, merged

2022-03-28 12:50 UTC, mfkenson commented on README.md
> +`git clone --recursive https://github.com/wsnewman/learning_ros_external_pkgs_noetic`
Sorry my mistake. The repo link should end with .git. However the recursive flag is necessary I believe.

2022-03-28 14:59 UTC, mfkenson commented on README.md
> +`git clone --recursive https://github.com/wsnewman/learning_ros_external_pkgs_noetic`
@leegs I tried the original https://github.com/wsnewman/learning_ros_external_packages but failed on both noetic and melodic, mainly due to missing baxter related packages. 

My only successful catkin_make is on noetic after running commands below.
```
mkdir -p ~/ros_ws/src/
cd ~/ros_ws/src/
git clone --recursive https://github.com/wsnewman/learning_ros.git
git clone --recursive https://github.com/wsnewman/learning_ros_external_pkgs_noetic.git
cd ~/ros_ws/
rosdep install --from-paths src --ignore-src -r -y
sudo apt install ros-noetic-moveit
catkin_make
```